### ISSUE TITLE
Does not work on a raspberry pi 4

### ISSUE THREAD

**Issue by incognito1234** [flowerysong/quickxorhash#1]
Hi,

It seems that this code does not work on a raspberry pi OS (perhaps due to 32 bits arch).

**Ubuntu 18.04.5 LTS**
```
$ uname -a
Linux ns379381 4.9.133-xxxx-std-ipv6-64 #413770 SMP Mon Oct 15 08:12:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ echo ab > ab.txt && ./quickxorhash ab.txt
YRCDAgAAAAAAAAAAAwAAAAAAAAA=
```
--> hash is confirmed if ab.txt is uploaded on onedrive.

**Raspbian GNU/Linux 10 (buster)**
```
$ uname -a
Linux rpi4 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
$ echo ab > ab.txt && ./quickxorhash ab.txt
YRCDAgAAAAAAAAAAAAAAAAMAAAA=
```

Cheers,
Jareth

**Comment by flowerysong** [comment]
I don't have ready access to a 32 bit environment, but I think 7d8a21555da02a68b562d6fde91b7cd604d5f9a4 should fix this issue.

**Comment by incognito1234** [comment]
It works perfectly.
Thank you
