### ISSUE TITLE
Large files are not supported on 32 bits environment

### ISSUE THREAD

**Issue by incognito1234** [flowerysong/quickxorhash#2]
On 32 bits environment, an error is raised when a large files (more the 4 Gb) are passed as argument.

```
$ls -hl ./large_file.tar.gz
-rw-r--r-- 1 jareth jareth 4,5G oct.   29 18:00  ./large_file.tar.gz
$ ./quickxorhash ./large_file.tar.gz
Failed to open ./large_file.tar.gz
```

The following patch fixes the issue
```
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,5 +1,5 @@
 ACLOCAL_AMFLAGS = -I m4
-AM_CFLAGS = -Wall -Wextra $(LIBCRYPTO_CFLAGS)
+AM_CFLAGS = -Wall -Wextra $(LIBCRYPTO_CFLAGS) -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1

 SUBDIRS = . test
```

**Comment by flowerysong** [comment]
51143f67470a0454f3a2e4f0dff84a881fa724a6 should address this without unconditionally adding extra compilation flags.

**Comment by incognito1234** [comment]
KO. Issue is still here

**Comment by flowerysong** [comment]
Ah, yep, it added the define to `config.h`, which wasn't included anywhere. 9cfb16542e2c5020d63f38f0f8e870786593ec64 adds the missing includes.

**Comment by incognito1234** [comment]
Much better. Tx
